<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(WindowsPackageTargetFrameworks)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CP.ReactiveUI.Primitives.Windows\CP.ReactiveUI.Primitives.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System" />
    <Using Include="ReactiveUI.Primitives" />
  </ItemGroup>
</Project>
