<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0-windows10.0.19041.0</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <NoWarn>$(NoWarn);NU1701;CA1859;PSH1000;PSH1100;PSH1414;SST1204;SST1210;SST1402;SST1429;SST1445;SST1471;SST1516;SST1523;SST1531;SST1532;SST1600;SST1624;SST1642;SST1649;SST1703;SST1705;SST2010;SST2011;SST2200;SST2202;SST2218;SST2221;SST2315;SST2328;SST2403</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CP.ReactiveUI.Primitives.Windows.Core\CP.ReactiveUI.Primitives.Windows.Core.csproj" />
    <ProjectReference Include="..\CP.ReactiveUI.Primitives.Windows.Reactive\CP.ReactiveUI.Primitives.Windows.Reactive.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ReactiveUI.Reactive" />
    <PackageReference Include="ReactiveUI.WPF.Reactive" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
</Project>
